### ISSUE TITLE
Add an expression language system

### ISSUE THREAD

**Issue by pith** [seedstack/coffig#2]
A simple EL system would be very useful to declare aliases, use custom piped functions (for cypting, default values, etc.)

Here is a sample of what it could be. A more strict grammar will be defined later.

_app.yml_

``` yaml
security:
  username: user1
  password: ${"45f4sq654fgq6s54" | decrypt(env.keystore, "sha-256") | trim() | or("password") }

database:
  url: ${etcd.services.toto.url}
```
